AppFood/urls.py
from . import views
from django.urls import path

app_name = 'AppFood'
urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('<int:pk>', views.FoodDetail.as_view(), name='detail'),
    path('item/', views.item, name='item'),

    # add items
    path('add/', views.CreateItem.as_view(), name='add'),
    # update items
    path('edit/<int:id>/', views.edit, name='edit'),
    # delete items
    path('delete/<int:id>/', views.delete, name='delete')
]

FoodMenuDjango/urls.py
from django.contrib import admin
from django.urls import include, path
from AppUser import views as user_views
from django.contrib.auth import views as autntication_viwes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppFood.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', autntication_viwes.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', autntication_viwes.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]



urlpatterns += [
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppFood/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,
                                  default="https://p.kindpng.com/picc/s/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png")

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("AppFood:detail", kwargs={"pk": self.pk})

AppFood/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

AppUser/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

AppFood/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import *
from .forms import *
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
"""def index(request):
    item_list = Item.objects.all()
    contex = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', contex)
"""


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('This is an item')


"""def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request, 'food/detail.html', context)
"""


class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'


"""def add(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('AppFood:index')
    return render(request, 'food/add.html', {'form': form})
"""


class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/add.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def edit(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('AppFood:index')

    return render(request, 'food/add.html', {'form': form, 'item': item})


def delete(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('AppFood:index')

    return render(request, 'food/delete.html', {'item': item})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Food App</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar  navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Food App</a>
    <div class="navbar">
        <a class="navbar-item nav-link" href="{% url 'AppFood:add' %}">Add Item</a>
        <a class="navbar-item nav-link" href="#">Delete Item</a>
        <a class="navbar-item nav-link" href="#">View Item</a>
        {% if user.is_authenticated %}
            <a class="navbar-item nav-link" href="{% url 'profile' %}">profile</a>
            <a class="navbar-item nav-link" href="{% url 'logout' %}">Logout</a>

        {% else %}
            <a class="navbar-item nav-link" href="{% url 'login' %}">Logout</a>
        {% endif %}
    </div>
</nav>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ massage.tags }}">    {{ message }} </div>

    {% endfor %}
{% endif %}
{% block body %}

{% endblock %}
</body>
</html>

templates/food/add.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

templates/food/delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are You sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>

templates/food/detail.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" width="300px" src="{{ item.item_image }}" class="card"/>

        </div>
    </div>

    <h1>{{ object.item_name }}</h1>
    <h5 align="justify">{{ object.item_desc }}</h5>
    <h1>${{ object.item_price }}</h1>
        <a href="{% url 'AppFood:delete' item.id %}">Delete</a>
{% endblock %}

templates/food/index.html
{% extends 'base.html' %}
{% load static %}

<h1> Food List</h1>
{% block body %}
    {% for i in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{ i.item_image }}">

            </div>
            <div class="col-md-4">
                <h3>{{ i.item_name }}</h3>
                <h5 align="justify">{{ i.item_desc }}</h5>
                <h2>${{ i.item_price }}</h2>

            </div>
            <div class="col-md-2">
                <a href="{% url 'AppFood:detail' i.id %}" class="btn btn-success"> Details</a>
                <a href="{% url 'AppFood:edit' i.id %}" class="btn btn-success"> Edit</a>

            </div>
        </div>

    {% endfor %}
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% block body %}
    <div class="content">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
            <div class="card-header">
            <div class="card-title">
 <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>
{% endblock %}
</div>
            </div>
        </div>
    </div>

    </div>

templates/user/logout.html
<h1> You have been logged out </h1>

templates/user/profile.html
<h1> {{ user.username }} </h1>
<img src="{{ user.profile.image.url }}">

templates/user/register.html
<form method="POST">
    {% csrf_token %}
  <h6>username   {{ form.username }}</h6>
    <h6>email      {{ form.email }}</h6>
    <h6>password 1 {{ form.password1 }}</h6>
    <h6>password 2 {{ form.password2 }}</h6>



    <button type="submit">Signup</button>
</form>